Exercicio2/Exercicio2/Models/Materia.cs
using Exercicio2.DAO;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace Exercicio2.Models
{
    public class Materia
    {
        public static List<Materia> materias = new Materia().retornaMaterias();
        public int Codigo { get; set; }
        public string Nome { get; set; }

        public List<Materia> retornaMaterias()
        {
            Xml dao = new Xml();

            DataSet dsMaterias = dao.retornaDadosEmXml();
            List<Materia> materia = new List<Materia>();
            materia = (from rows in dsMaterias.Tables[0].AsEnumerable()
                       select new Materia
                       {
                           Nome = rows[0].ToString(),
                           Codigo = Convert.ToInt32(rows[1].ToString())
                       }).ToList();

            return materia;
        }

        public void adicionaNovaMateria(Materia materia)
        {
            materias.Add(new Materia()
            {
                Codigo = materias.OrderByDescending(o => o.Codigo).Select(x => x.Codigo).FirstOrDefault() + 1,
                Nome = materia.Nome
            });
        }
    }


}

Exercicio2/Exercicio2/Controllers/HomeController.cs
using Exercicio2.Models;
using System.Web.Mvc;

namespace Exercicio2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        { 
            ViewBag.Materias = new SelectList
                (
                    Materia.materias,
                    "Codigo",
                    "Nome"
                );

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Exercicio2/Exercicio2/Controllers/MateriaController.cs
using Exercicio2.Models;
using System.Web.Mvc;

namespace Exercicio2.Controllers
{
    public class MateriaController : Controller
    {
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Materia materia)
        {
            if (ModelState.IsValid)
            {
                var novaMateria = new Materia();

                novaMateria.adicionaNovaMateria(materia);
            }
            return RedirectToAction("Create");
        }
    }
}

Exercicio2/Exercicio2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Autor: Thiago H. Pereira, Mobile and Web Developer, email: thiagohenrique.ti@gmail.com, tel: (31) 99368-6458.</p>

Exercicio2/Exercicio2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Exercicio2/Exercicio2/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Home Page";
}

<div class="jumbotron">
	<h1>ASP.NET</h1>
	<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
	<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">

	<h2>RESPOSTAS PARA O DESAFIO</h2>
	<div class="col-md-4">
		1 - Clique para expandir a imagem

		<a href="~/Exercicio 1/exercicio1.jpg" target="_blank">
			<img src="~/Exercicio 1/exercicio1.jpg" width="250" height="400" />
		</a>
	</div>

	<div class="col-md-4">
		2 - Escolha a matéria:

		@Html.DropDownList("Materias", String.Empty)
		<br />
		<br />
		<p><input type="button" class="btn btn-primary" value="Adicionar mais matérias" onclick="location.href='@Url.Action("Create", "Materia")'" /></p>

	</div>
	<div class="col-md-4">
		3 - Resposta:

		<p>d</p>

		<p>Nota: Eu fiquei confuso com as alterantivas e vou detalhar a solução abaixo. Eu quebraria toda a estrutura e agruparia todos os contextos em pequenas pacotes (Nuget por exemplo) e registraria todas estes pacotes em uma camada (business ou então em um projeto separado pois poderia até ser evoluído para um REST API que ofereceria somente os serviços de lógica do negócio) e deixaria exposto suas interfaces para a implementação nos clientes (não sei se eu também seria o responsável por manter os clientes).</p>

	</div>
</div>
<div class="row">
	<div class="col-md-4">
		4 - Resposta:
		<p>c</p>
	</div>
	<div class="col-md-4">
		5 - Resposta:
		<p>e</p>
	</div>
	<div class="col-md-4">
		6 - Resposta:
		<p>d</p>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		7 - Resposta:
		<p>b</p>
	</div>
	<div class="col-md-4">
		8 - Resposta:
		<p>b</p>
	</div>
	<div class="col-md-4">
		9 - Resposta:
		<p>c</p>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		10 - Resposta:

		Existe um projeto no diretório superior com o nome Exercíco10;
		<p></p>
	</div>

</div>

Exercicio2/Exercicio2/Views/Materia/Create.cshtml
@model Exercicio2.Models.Materia

@{
    ViewBag.Title = "Nova Matéria";
}

<h2>View</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Exercicio2/Exercicio2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Desafio MONTREAL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Desafio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Respostas", "Index", "Home")</li>
                    <li>@Html.ActionLink("Autor", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>